openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /watch/{id}:
    get:
      operationId: watch_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchList'
          description: ''
    put:
      operationId: watch_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WatchList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/WatchList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/WatchList'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchList'
          description: ''
    delete:
      operationId: watch_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /watch/{id}/review-create/:
    post:
      operationId: watch_review_create_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Review'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
  /watch/{id}/review-list/:
    get:
      operationId: watch_review_list_list
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
          description: ''
  /watch/list/:
    get:
      operationId: watch_list_retrieve
      tags:
      - watch
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchList'
          description: ''
    post:
      operationId: watch_list_create
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WatchList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/WatchList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/WatchList'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchList'
          description: ''
  /watch/review/{id}/:
    get:
      operationId: watch_review_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
    put:
      operationId: watch_review_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Review'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
    patch:
      operationId: watch_review_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedReview'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedReview'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedReview'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
          description: ''
    delete:
      operationId: watch_review_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - watch
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /watch/stream-platform/:
    get:
      operationId: watch_stream_platform_list
      tags:
      - watch
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StreamPlatform'
          description: ''
    post:
      operationId: watch_stream_platform_create
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
  /watch/stream-platform/{id}/:
    get:
      operationId: watch_stream_platform_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - watch
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
    put:
      operationId: watch_stream_platform_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/StreamPlatform'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
    patch:
      operationId: watch_stream_platform_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - watch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedStreamPlatform'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedStreamPlatform'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedStreamPlatform'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamPlatform'
          description: ''
    delete:
      operationId: watch_stream_platform_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream platform.
        required: true
      tags:
      - watch
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    PatchedReview:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        rating:
          type: integer
          maximum: 5
          minimum: 1
        description:
          type: string
          nullable: true
          maxLength: 200
        active:
          type: boolean
        created:
          type: string
          format: date-time
          readOnly: true
        update:
          type: string
          format: date-time
          readOnly: true
    PatchedStreamPlatform:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        watchlist_set:
          type: array
          items:
            $ref: '#/components/schemas/WatchList'
          readOnly: true
        name:
          type: string
          maxLength: 50
        about:
          type: string
          maxLength: 200
        website:
          type: string
          format: uri
          maxLength: 100
    Review:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        rating:
          type: integer
          maximum: 5
          minimum: 1
        description:
          type: string
          nullable: true
          maxLength: 200
        active:
          type: boolean
        created:
          type: string
          format: date-time
          readOnly: true
        update:
          type: string
          format: date-time
          readOnly: true
      required:
      - created
      - id
      - rating
      - update
    StreamPlatform:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        watchlist_set:
          type: array
          items:
            $ref: '#/components/schemas/WatchList'
          readOnly: true
        name:
          type: string
          maxLength: 50
        about:
          type: string
          maxLength: 200
        website:
          type: string
          format: uri
          maxLength: 100
      required:
      - about
      - id
      - name
      - watchlist_set
      - website
    WatchList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        review_set:
          type: array
          items:
            $ref: '#/components/schemas/Review'
          readOnly: true
        title:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        storyline:
          type: string
          maxLength: 200
        active:
          type: boolean
        created:
          type: string
          format: date-time
          readOnly: true
        platform:
          type: integer
          nullable: true
      required:
      - created
      - id
      - review_set
      - storyline
      - title
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
