# Generated by Django 5.2.8 on 2025-11-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.IntegerField(),
        ),
    ]
