# Generated by Django 5.2.8 on 2025-11-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_alter_watchlist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
